#pragma once

/*
 * Taken from GLFW/glfw3.h
 */

#define COSEC_MOUSE_BUTTON_1      0
#define COSEC_MOUSE_BUTTON_2      1
#define COSEC_MOUSE_BUTTON_3      2
#define COSEC_MOUSE_BUTTON_4      3
#define COSEC_MOUSE_BUTTON_5      4
#define COSEC_MOUSE_BUTTON_6      5
#define COSEC_MOUSE_BUTTON_7      6
#define COSEC_MOUSE_BUTTON_8      7
#define COSEC_MOUSE_BUTTON_LAST   COSEC_MOUSE_BUTTON_8
#define COSEC_MOUSE_BUTTON_LEFT   COSEC_MOUSE_BUTTON_1
#define COSEC_MOUSE_BUTTON_RIGHT  COSEC_MOUSE_BUTTON_2
#define COSEC_MOUSE_BUTTON_MIDDLE COSEC_MOUSE_BUTTON_3
